global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - "rules/*.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'model-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api:8080']

  - job_name: 'model-metrics'
    metrics_path: '/model-metrics'
    static_configs:
      - targets: ['api:8080']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100'] 